### ISSUE TITLE
[cudapoa] Expose compile-time constants as parameters

### ISSUE THREAD

**Issue by cjw85** [clara-genomics/ClaraGenomicsAnalysis#170] opened 2019-10-04 08:49 UTC
There are several constants defined in `cudapoa_kernels.cuh` which control various maximum sizes of graph properties. It would be useful to vary these at runtime.

**Comment by tijyojwad** [comment] 2020-04-10 21:02
Added support for this to C++ API in #327

**Comment by tijyojwad** [comment] 2020-04-10 21:03
Also a duplicate of #299 , closing this one as progress is tracked there

**Closed by tijyojwad** 2020-04-10 21:03 UTC
Labels: enhancement, pyclaragenomics
